/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InputWrapper {
        /**
          * Disabled
         */
        "disabled": boolean;
    }
}
declare global {
    interface HTMLInputWrapperElement extends Components.InputWrapper, HTMLStencilElement {
    }
    var HTMLInputWrapperElement: {
        prototype: HTMLInputWrapperElement;
        new (): HTMLInputWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "input-wrapper": HTMLInputWrapperElement;
    }
}
declare namespace LocalJSX {
    interface InputWrapper {
        /**
          * Disabled
         */
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "input-wrapper": InputWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "input-wrapper": LocalJSX.InputWrapper & JSXBase.HTMLAttributes<HTMLInputWrapperElement>;
        }
    }
}
